kind: OpenLibertyApplication
apiVersion: apps.openliberty.io/v1
metadata:
  name: modresorts-container
  namespace: rlange
spec:
  applicationImage: rlangehennig/modresorts:1.0
  expose: true
  manageTLS: true
  replicas: 1
  service:
    type: ClusterIP
    port: 9080
  serviceAccount:
    mountToken: true
