kind: OpenLibertyApplication
apiVersion: apps.openliberty.io/v1
metadata:
  name: modresorts-container
  namespace: rlange
spec:
  # broken image
  #applicationImage: rlangehennig/modresorts:89bdffaa
  # good image
  #applicationImage: rlangehennig/modresorts:2b9e208a
  applicationImage: rlangehennig/modresorts:cd662abd
  expose: true
  manageTLS: false
  replicas: 1
